version: '3.1'
services:
  wordpress:
    image: wordpress:latest
    restart: always
    volumes:
    - wordpress:/var/www/html
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      WORDPRESS_DB_NAME: dbtest
      WORDPRESS_DB_HOST: dbtest0001.mysql.database.azure.com
      WORDPRESS_DB_PASSWORD: P@$$w0rd
      WORDPRESS_DB_USER: dbuser

volumes:
  wordpress: